apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: hacbs-test-project-zihj
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: hacbs-test-project-zihj
    app.kubernetes.io/part-of: rhtap-demo-app
  name: hacbs-test-project-zihj
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: hacbs-jvm-build-test-project
      app.kubernetes.io/instance: hacbs-test-project-zihj
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: hacbs-jvm-build-test-project
        app.kubernetes.io/instance: hacbs-test-project-zihj
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/rhtap-demo-gifs-tenant/rhtap-demo-app/hacbs-test-project-zihj@sha256:cdc7a90b864be2cc2d45d552882b6f9a2c7918b6bb820d5ad06be91780cb7e1d
        name: hacbs-jvm-build-test-project
        ports:
        - containerPort: 8081
          name: http
          protocol: TCP
        resources:
          limits:
            cpu: 500m
            memory: 1Gi
status: {}
